package com.quantma.lite.sas

import kotlin.math.abs

/**
 * Secure Agent Shell — Code Validator.
 *
 * Validates code generated by small LLMs before writing to disk.
 * Catches common mistakes that small models make:
 *
 * - Unmatched brackets `{}/[]/()` — model forgot to close a block
 * - Unclosed string literals — model broke a string mid-generation
 * - Structural regression — model "lost" functions/classes when rewriting
 * - Content loss — model output is suspiciously shorter than the original
 * - Encoding artifacts — literal `\n` instead of actual newlines
 *
 * When possible, applies auto-fixes (e.g., closing unclosed brackets).
 * Returns [ValidationResult] with errors, warnings, and optionally fixed content.
 */
class CodeValidator {

    /**
     * Validate code content before writing.
     *
     * @param newContent The code the LLM wants to write
     * @param oldContent The current file content (null for new files)
     * @param fileName File name for language detection
     * @return [ValidationResult] with validation status and optional auto-fix
     */
    fun validate(
        newContent: String,
        oldContent: String? = null,
        fileName: String = ""
    ): ValidationResult {
        if (newContent.isBlank()) {
            return ValidationResult(
                valid = false,
                errors = listOf(
                    ValidationError(
                        ValidationType.EMPTY_CONTENT,
                        "Generated content is empty",
                        severity = ValidationSeverity.CRITICAL
                    )
                )
            )
        }

        val language = CodeLanguage.fromExtension(fileName.substringAfterLast('.', ""))
        val errors = mutableListOf<ValidationError>()
        val warnings = mutableListOf<String>()
        var fixedContent: String? = null

        // 1. Check for encoding artifacts and fix
        val encodingFixed = fixEncodingArtifacts(newContent)
        if (encodingFixed != newContent) {
            warnings.add("Fixed encoding artifacts (literal \\n, \\t)")
            fixedContent = encodingFixed
        }

        val contentToCheck = fixedContent ?: newContent

        // 2. Bracket matching
        val bracketResult = checkBrackets(contentToCheck, language)
        errors.addAll(bracketResult.errors)
        if (bracketResult.autoFixed != null) {
            fixedContent = bracketResult.autoFixed
            warnings.add("Auto-closed ${bracketResult.errors.size} unmatched bracket(s)")
        }

        // 3. String literal check
        val stringErrors = checkStringLiterals(contentToCheck, language)
        errors.addAll(stringErrors)

        // 4. Structural regression (only if we have old content)
        if (oldContent != null && oldContent.isNotBlank()) {
            val regressionResult = checkStructuralRegression(contentToCheck, oldContent, language)
            errors.addAll(regressionResult.errors)
            warnings.addAll(regressionResult.warnings)
        }

        // 5. Content loss check
        if (oldContent != null && oldContent.isNotBlank()) {
            val lossResult = checkContentLoss(contentToCheck, oldContent)
            errors.addAll(lossResult)
        }

        // 6. Dangerous pattern scan (warns about runtime code execution primitives)
        val dangerWarnings = scanDangerousPatterns(contentToCheck, language, fileName)
        warnings.addAll(dangerWarnings)

        return ValidationResult(
            valid = errors.none { it.severity == ValidationSeverity.CRITICAL || it.severity == ValidationSeverity.ERROR },
            errors = errors,
            warnings = warnings,
            autoFixed = fixedContent
        )
    }

    /**
     * Quick check: fast critical-only validation.
     * Returns a [ValidationResult] with only critical issues (empty content, content loss).
     * Faster than full [validate] — skips bracket matching, structural regression, etc.
     */
    fun quickCheck(newContent: String, fileName: String, oldContent: String? = null): ValidationResult {
        val errors = mutableListOf<ValidationError>()

        if (newContent.isBlank()) {
            errors.add(ValidationError(
                type = ValidationType.EMPTY_CONTENT,
                message = "Content is empty or blank",
                severity = ValidationSeverity.CRITICAL
            ))
        }

        if (oldContent != null && oldContent.isNotBlank() && newContent.isNotBlank()) {
            val ratio = newContent.length.toDouble() / oldContent.length.toDouble()
            if (ratio < CRITICAL_LOSS_RATIO) {
                errors.add(ValidationError(
                    type = ValidationType.CONTENT_LOSS,
                    message = "Content reduced to ${(ratio * 100).toInt()}% of original (threshold: ${(CRITICAL_LOSS_RATIO * 100).toInt()}%)",
                    severity = ValidationSeverity.CRITICAL
                ))
            } else if (ratio < WARNING_LOSS_RATIO) {
                errors.add(ValidationError(
                    type = ValidationType.CONTENT_LOSS,
                    message = "Content reduced to ${(ratio * 100).toInt()}% of original",
                    severity = ValidationSeverity.WARNING
                ))
            }
        }

        return ValidationResult(
            valid = errors.none { it.severity == ValidationSeverity.CRITICAL },
            errors = errors
        )
    }

    // ═══════════════════════════════════════════════════════════════════════
    // Bracket Matching
    // ═══════════════════════════════════════════════════════════════════════

    private data class BracketCheckResult(
        val errors: List<ValidationError>,
        val autoFixed: String?
    )

    private fun checkBrackets(content: String, language: CodeLanguage): BracketCheckResult {
        // XML has different structure — skip bracket check
        if (language == CodeLanguage.XML) return BracketCheckResult(emptyList(), null)

        val stack = mutableListOf<BracketInfo>()
        val errors = mutableListOf<ValidationError>()
        var inString = false
        var stringChar = ' '
        var inLineComment = false
        var inBlockComment = false
        var i = 0
        val lines = content.lines()
        var currentLine = 1

        while (i < content.length) {
            val ch = content[i]
            val next = if (i + 1 < content.length) content[i + 1] else ' '

            // Track line numbers
            if (ch == '\n') {
                currentLine++
                inLineComment = false
                i++
                continue
            }

            // Skip comments
            if (!inString && !inBlockComment && ch == '/' && next == '/') {
                inLineComment = true; i += 2; continue
            }
            if (!inString && !inLineComment && ch == '/' && next == '*') {
                inBlockComment = true; i += 2; continue
            }
            if (inBlockComment && ch == '*' && next == '/') {
                inBlockComment = false; i += 2; continue
            }
            if (inLineComment || inBlockComment) { i++; continue }

            // Track strings
            if (!inString && (ch == '"' || ch == '\'')) {
                // Python triple quotes
                if (language == CodeLanguage.PYTHON && i + 2 < content.length &&
                    content[i + 1] == ch && content[i + 2] == ch) {
                    i += 3; continue // Skip triple quotes (simplified)
                }
                inString = true; stringChar = ch; i++; continue
            }
            if (inString) {
                if (ch == '\\') { i += 2; continue } // Skip escaped chars
                if (ch == stringChar) { inString = false }
                i++; continue
            }

            // Track brackets
            when (ch) {
                '{', '(', '[' -> stack.add(BracketInfo(ch, currentLine))
                '}', ')', ']' -> {
                    val expected = closingToOpening(ch)
                    if (stack.isNotEmpty() && stack.last().char == expected) {
                        stack.removeLast()
                    } else {
                        errors.add(ValidationError(
                            ValidationType.UNMATCHED_BRACKET,
                            "Unexpected closing bracket '$ch'",
                            line = currentLine
                        ))
                    }
                }
            }
            i++
        }

        // Unclosed brackets
        for (bracket in stack.reversed()) {
            errors.add(ValidationError(
                ValidationType.UNMATCHED_BRACKET,
                "Unclosed '${bracket.char}' opened at line ${bracket.line}",
                line = bracket.line
            ))
        }

        // Try to auto-fix unclosed brackets
        var fixed: String? = null
        if (stack.isNotEmpty() && errors.size <= MAX_AUTO_FIX_BRACKETS) {
            val sb = StringBuilder(content)
            for (bracket in stack.reversed()) {
                sb.append('\n')
                sb.append(openingToClosing(bracket.char))
            }
            fixed = sb.toString()
        }

        return BracketCheckResult(errors, fixed)
    }

    private data class BracketInfo(val char: Char, val line: Int)

    private fun closingToOpening(ch: Char): Char = when (ch) {
        '}' -> '{'; ')' -> '('; ']' -> '['; else -> ch
    }

    private fun openingToClosing(ch: Char): Char = when (ch) {
        '{' -> '}'; '(' -> ')'; '[' -> ']'; else -> ch
    }

    // ═══════════════════════════════════════════════════════════════════════
    // String Literal Check
    // ═══════════════════════════════════════════════════════════════════════

    private fun checkStringLiterals(content: String, language: CodeLanguage): List<ValidationError> {
        val errors = mutableListOf<ValidationError>()

        content.lines().forEachIndexed { idx, line ->
            val lineNum = idx + 1
            val trimmed = line.trim()

            // Skip comments
            if (trimmed.startsWith("//") || trimmed.startsWith("#") || trimmed.startsWith("*")) return@forEachIndexed

            // Count unescaped quotes
            var doubleQuotes = 0
            var singleQuotes = 0
            var i = 0
            while (i < trimmed.length) {
                if (trimmed[i] == '\\') { i += 2; continue }
                when (trimmed[i]) {
                    '"' -> doubleQuotes++
                    '\'' -> {
                        // In Kotlin/Java, single quotes are char literals (always paired)
                        if (language != CodeLanguage.PYTHON) {
                            // Skip — char literals are usually short
                        } else {
                            singleQuotes++
                        }
                    }
                }
                i++
            }

            // Odd number of double quotes = unclosed string
            if (doubleQuotes % 2 != 0) {
                // Exception: multi-line strings with triple quotes
                if (!trimmed.contains("\"\"\"")) {
                    errors.add(ValidationError(
                        ValidationType.UNCLOSED_STRING,
                        "Possibly unclosed string literal on line $lineNum",
                        line = lineNum,
                        severity = ValidationSeverity.WARNING
                    ))
                }
            }
        }

        return errors
    }

    // ═══════════════════════════════════════════════════════════════════════
    // Structural Regression
    // ═══════════════════════════════════════════════════════════════════════

    private data class StructuralResult(
        val errors: List<ValidationError>,
        val warnings: List<String>
    )

    private fun checkStructuralRegression(
        newContent: String,
        oldContent: String,
        language: CodeLanguage
    ): StructuralResult {
        val errors = mutableListOf<ValidationError>()
        val warnings = mutableListOf<String>()

        val oldSymbols = extractSymbols(oldContent, language)
        val newSymbols = extractSymbols(newContent, language)

        // Check for lost symbols
        val lostSymbols = oldSymbols - newSymbols
        if (lostSymbols.isNotEmpty() && lostSymbols.size > oldSymbols.size * 0.3) {
            errors.add(ValidationError(
                ValidationType.STRUCTURAL_REGRESSION,
                "Lost ${lostSymbols.size} symbols: ${lostSymbols.take(5).joinToString(", ")}",
                severity = ValidationSeverity.ERROR
            ))
        } else if (lostSymbols.isNotEmpty()) {
            warnings.add("Removed symbols: ${lostSymbols.take(5).joinToString(", ")}")
        }

        // Check import count regression
        val oldImports = countPattern(oldContent, IMPORT_PATTERNS[language])
        val newImports = countPattern(newContent, IMPORT_PATTERNS[language])
        if (oldImports > 0 && newImports == 0) {
            errors.add(ValidationError(
                ValidationType.STRUCTURAL_REGRESSION,
                "All imports were removed ($oldImports → 0)",
                severity = ValidationSeverity.ERROR
            ))
        }

        return StructuralResult(errors, warnings)
    }

    /**
     * Extract symbol names (functions, classes) from code.
     */
    private fun extractSymbols(content: String, language: CodeLanguage): Set<String> {
        val symbols = mutableSetOf<String>()
        val patterns = SYMBOL_PATTERNS[language] ?: return symbols

        for (pattern in patterns) {
            pattern.findAll(content).forEach { match ->
                match.groupValues.getOrNull(1)?.let { symbols.add(it) }
            }
        }

        return symbols
    }

    private fun countPattern(content: String, pattern: Regex?): Int {
        return pattern?.findAll(content)?.count() ?: 0
    }

    // ═══════════════════════════════════════════════════════════════════════
    // Content Loss Check
    // ═══════════════════════════════════════════════════════════════════════

    private fun checkContentLoss(newContent: String, oldContent: String): List<ValidationError> {
        val errors = mutableListOf<ValidationError>()

        val oldLines = oldContent.lines().size
        val newLines = newContent.lines().size
        val ratio = newLines.toDouble() / oldLines.toDouble()

        // Critical: lost more than 50% of lines
        if (ratio < CRITICAL_LOSS_RATIO && oldLines > 10) {
            errors.add(ValidationError(
                ValidationType.CONTENT_LOSS,
                "Content reduced by ${((1 - ratio) * 100).toInt()}% ($oldLines → $newLines lines). " +
                    "The model may have lost content during rewrite.",
                severity = ValidationSeverity.CRITICAL
            ))
        }
        // Warning: lost more than 30% of lines
        else if (ratio < WARNING_LOSS_RATIO && oldLines > 10) {
            errors.add(ValidationError(
                ValidationType.CONTENT_LOSS,
                "Content reduced by ${((1 - ratio) * 100).toInt()}% ($oldLines → $newLines lines)",
                severity = ValidationSeverity.WARNING
            ))
        }

        // Check for suspiciously large size increase (model may have duplicated content)
        if (ratio > 3.0 && oldLines > 10) {
            errors.add(ValidationError(
                ValidationType.CONTENT_LOSS,
                "Content tripled in size ($oldLines → $newLines lines). Possible duplication.",
                severity = ValidationSeverity.WARNING
            ))
        }

        return errors
    }

    // ═══════════════════════════════════════════════════════════════════════
    // Dangerous Pattern Scan
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * Scan for patterns that indicate runtime code execution, shell invocation,
     * or filesystem access outside the sandbox.
     *
     * This is a WARNING-only check — it never blocks writes. The goal is to
     * surface suspicious LLM-generated code for user review before it is saved.
     *
     * Patterns are intentionally conservative: they match the function/method
     * name in context to reduce false positives (e.g. `eval(` not just `eval`).
     *
     * @param content Code to scan
     * @param language Detected language
     * @param fileName File name for display in warnings
     * @return List of warning strings, empty if nothing suspicious found
     */
    private fun scanDangerousPatterns(
        content: String,
        language: CodeLanguage,
        fileName: String
    ): List<String> {
        // MD/TXT/config files: skip scan (not executable code)
        val ext = fileName.substringAfterLast('.', "").lowercase()
        if (ext in SCAN_SKIP_EXTENSIONS) return emptyList()

        val warnings = mutableListOf<String>()
        val patterns = DANGEROUS_PATTERNS[language] ?: DANGEROUS_PATTERNS_GENERIC

        for ((label, pattern) in patterns) {
            val matches = pattern.findAll(content)
            val count = matches.count()
            if (count > 0) {
                val firstLine = content.lines().indexOfFirst { pattern.containsMatchIn(it) } + 1
                warnings.add("Dangerous pattern [$label] found ($count occurrence(s), first at line $firstLine)")
            }
        }

        return warnings
    }

    // ═══════════════════════════════════════════════════════════════════════
    // Encoding Artifact Fix
    // ═══════════════════════════════════════════════════════════════════════

    /**
     * Fix common encoding artifacts from LLM output.
     * Small models often generate literal `\n` instead of actual newlines.
     */
    private fun fixEncodingArtifacts(content: String): String {
        var fixed = content

        // Fix literal \n that should be newlines (but NOT inside actual string literals)
        // Heuristic: if the content has very few actual newlines but many literal \n, fix them
        val actualNewlines = content.count { it == '\n' }
        val literalNewlines = Regex("""(?<!\\)\\n""").findAll(content).count()

        if (actualNewlines < 3 && literalNewlines > 3) {
            // Likely the whole content is on one line with literal \n
            fixed = fixed.replace("\\n", "\n")
            fixed = fixed.replace("\\t", "\t")
        }

        return fixed
    }

    companion object {
        const val CRITICAL_LOSS_RATIO = 0.5   // Block if <50% of original
        const val WARNING_LOSS_RATIO = 0.7     // Warn if <70% of original
        const val MAX_AUTO_FIX_BRACKETS = 3    // Don't auto-fix if too many errors

        // Symbol extraction patterns per language
        private val SYMBOL_PATTERNS = mapOf(
            CodeLanguage.KOTLIN to listOf(
                Regex("""(?:fun|class|object|interface|enum)\s+(\w+)"""),
                Regex("""(?:val|var)\s+(\w+)""")
            ),
            CodeLanguage.JAVA to listOf(
                Regex("""(?:class|interface|enum)\s+(\w+)"""),
                Regex("""(?:public|private|protected|static)?\s*\w+\s+(\w+)\s*\(""")
            ),
            CodeLanguage.PYTHON to listOf(
                Regex("""(?:def|class)\s+(\w+)""")
            ),
            CodeLanguage.CPP to listOf(
                Regex("""(?:class|struct|enum)\s+(\w+)"""),
                Regex("""(?:\w+\s+)+(\w+)\s*\([^)]*\)\s*\{""")
            ),
            CodeLanguage.JAVASCRIPT to listOf(
                Regex("""(?:function|class)\s+(\w+)"""),
                Regex("""(?:const|let|var)\s+(\w+)\s*=""")
            ),
            CodeLanguage.RUST to listOf(
                Regex("""(?:fn|struct|enum|trait|impl)\s+(\w+)""")
            ),
            CodeLanguage.GO to listOf(
                Regex("""(?:func|type)\s+(\w+)""")
            )
        )

        // Import patterns per language
        private val IMPORT_PATTERNS = mapOf(
            CodeLanguage.KOTLIN to Regex("""^import\s""", RegexOption.MULTILINE),
            CodeLanguage.JAVA to Regex("""^import\s""", RegexOption.MULTILINE),
            CodeLanguage.PYTHON to Regex("""^(?:import|from)\s""", RegexOption.MULTILINE),
            CodeLanguage.CPP to Regex("""^#include\s""", RegexOption.MULTILINE),
            CodeLanguage.JAVASCRIPT to Regex("""^import\s""", RegexOption.MULTILINE),
            CodeLanguage.RUST to Regex("""^use\s""", RegexOption.MULTILINE),
            CodeLanguage.GO to Regex("""^import\s""", RegexOption.MULTILINE)
        )

        // Extensions exempt from dangerous-pattern scanning (not executable code)
        private val SCAN_SKIP_EXTENSIONS = setOf(
            "md", "txt", "json", "yaml", "yml", "toml", "properties",
            "cfg", "gitignore", "xml", "html", "css", "scss", "svg"
        )

        /**
         * Generic dangerous-pattern rules applied to all languages unless overridden.
         * Each entry: label → pattern.
         *
         * Patterns target the call site (with `(` or similar) to reduce false positives
         * from variable names or comments that happen to contain the keyword.
         */
        private val DANGEROUS_PATTERNS_GENERIC: List<Pair<String, Regex>> = listOf(
            "shell-exec"    to Regex("""Runtime\.getRuntime\(\)\.exec\("""),
            "process-exec"  to Regex("""ProcessBuilder\s*\("""),
            "reflection"    to Regex("""Class\.forName\s*\(""")
        )

        private val DANGEROUS_PATTERNS: Map<CodeLanguage, List<Pair<String, Regex>>> = mapOf(
            CodeLanguage.PYTHON to listOf(
                "eval"          to Regex("""\beval\s*\("""),
                "exec"          to Regex("""\bexec\s*\("""),
                "subprocess"    to Regex("""\bsubprocess\s*\."""),
                "os-system"     to Regex("""\bos\.system\s*\("""),
                "os-popen"      to Regex("""\bos\.popen\s*\("""),
                "open-write"    to Regex("""\bopen\s*\([^)]*['"]\s*w"""),
                "shutil-rmtree" to Regex("""\bshutil\.rmtree\s*\("""),
                "compile"       to Regex("""\bcompile\s*\(""")
            ),
            CodeLanguage.JAVASCRIPT to listOf(
                "eval"          to Regex("""\beval\s*\("""),
                "function-ctor" to Regex("""new\s+Function\s*\("""),
                "child-process" to Regex("""require\s*\(\s*['"]child_process['"]\s*\)"""),
                "exec-sync"     to Regex("""\.execSync\s*\("""),
                "spawn"         to Regex("""\.spawn\s*\("""),
                "fs-unlink"     to Regex("""fs\.unlink(?:Sync)?\s*\("""),
                "fs-rmdir"      to Regex("""fs\.rmdirSync\s*\(""")
            ),
            CodeLanguage.KOTLIN to listOf(
                "runtime-exec"  to Regex("""Runtime\.getRuntime\(\)\.exec\("""),
                "process-build" to Regex("""ProcessBuilder\s*\("""),
                "reflection"    to Regex("""Class\.forName\s*\("""),
                "dangerous-del" to Regex("""\.deleteRecursively\s*\(\s*\)""")
            ),
            CodeLanguage.JAVA to listOf(
                "runtime-exec"  to Regex("""Runtime\.getRuntime\(\)\.exec\("""),
                "process-build" to Regex("""ProcessBuilder\s*\("""),
                "reflection"    to Regex("""Class\.forName\s*\(""")
            ),
            CodeLanguage.GO to listOf(
                "exec-command"  to Regex("""exec\.Command\s*\("""),
                "os-remove-all" to Regex("""os\.RemoveAll\s*\(""")
            ),
            CodeLanguage.RUST to listOf(
                "process-cmd"   to Regex("""std::process::Command::new\s*\("""),
                "remove-dir"    to Regex("""fs::remove_dir_all\s*\(""")
            )
        )
    }
}
