package com.quantma.lite.sas

import java.util.UUID

/**
 * Secure Agent Shell (SAS) — Domain Models.
 *
 * Defines the structured protocol between LLM and the Android file system executor.
 * All tool interactions go through ToolCommand → ShellExecutor → ToolResponse.
 */

// ─── Tool Types ─────────────────────────────────────────────────────────────

/**
 * Enumeration of all available tools the LLM agent can invoke.
 */
enum class ToolType(val toolName: String) {
    READ_FILE("read_file"),
    WRITE_FILE("write_file"),
    CREATE_FILE("create_file"),
    APPEND_FILE("append_file"),
    LIST_DIR("list_dir"),
    SEARCH_GREP("search_grep"),
    GET_DIFF("get_diff"),
    GIT_STATUS("git_status"),
    GIT_ADD("git_add"),
    GIT_COMMIT("git_commit"),
    GIT_LOG("git_log"),
    GIT_BRANCH("git_branch"),

    // v3.1 — File Operations
    DELETE_FILE("delete_file"),

    // v3.1 — Code Quality (Group B)
    LINT_FILE("lint_file"),
    FORMAT_FILE("format_file"),
    COUNT_LINES("count_lines"),
    FIND_TODO("find_todo"),

    // v3.1 — Extended Git (Group A)
    GIT_STATUS_DETAILED("git_status_detailed"),
    GIT_COMMIT_AUTO("git_commit_auto"),
    GIT_PUSH_SAFE("git_push_safe"),
    GIT_STASH("git_stash"),

    // Branch / Merge operations
    GIT_CREATE_BRANCH("git_create_branch"),
    GIT_CHECKOUT("git_checkout"),
    GIT_DELETE_BRANCH("git_delete_branch"),
    GIT_MERGE("git_merge"),

    DONE("done");

    enum class Category(val label: String) {
        FILE_OPS("File Operations"),
        SEARCH("Search & Analysis"),
        GIT("Git"),
        CODE_QUALITY("Code Quality"),
        AGENT("Agent Control")
    }

    val category: Category get() = when (this) {
        READ_FILE, WRITE_FILE, CREATE_FILE, APPEND_FILE, LIST_DIR, DELETE_FILE -> Category.FILE_OPS
        SEARCH_GREP, GET_DIFF -> Category.SEARCH
        GIT_STATUS, GIT_ADD, GIT_COMMIT, GIT_LOG, GIT_BRANCH,
        GIT_STATUS_DETAILED, GIT_COMMIT_AUTO, GIT_PUSH_SAFE, GIT_STASH,
        GIT_CREATE_BRANCH, GIT_CHECKOUT, GIT_DELETE_BRANCH, GIT_MERGE -> Category.GIT
        LINT_FILE, FORMAT_FILE, COUNT_LINES, FIND_TODO -> Category.CODE_QUALITY
        DONE -> Category.AGENT
    }

    companion object {
        private val byName = entries.associateBy { it.toolName }

        fun fromName(name: String): ToolType? = byName[name.lowercase().trim()]
    }
}

// ─── Tool Command (LLM → Executor) ──────────────────────────────────────────

/**
 * A structured command generated by the LLM.
 *
 * JSON format:
 * ```json
 * {
 *   "id": "uuid",
 *   "tool": "read_file",
 *   "args": { "path": "src/main.kt" },
 *   "thought": "I need to read the file first"
 * }
 * ```
 */
data class ToolCommand(
    val id: String = UUID.randomUUID().toString(),
    val tool: ToolType,
    val args: Map<String, Any> = emptyMap(),
    val thought: String? = null
) {
    /** Convenience: get a string argument by key. */
    fun stringArg(key: String): String? = args[key]?.toString()

    /** Convenience: get a string argument or throw. */
    fun requireStringArg(key: String): String =
        stringArg(key) ?: throw IllegalArgumentException("Missing required argument: $key")

    /** Convenience: get an int argument with default. */
    fun intArg(key: String, default: Int): Int =
        (args[key] as? Number)?.toInt() ?: args[key]?.toString()?.toIntOrNull() ?: default

    /** Convenience: get a list of strings argument. */
    @Suppress("UNCHECKED_CAST")
    fun stringListArg(key: String): List<String> =
        (args[key] as? List<*>)?.mapNotNull { it?.toString() } ?: emptyList()
}

// ─── Tool Response (Executor → LLM / UI) ────────────────────────────────────

/**
 * Result of executing a ToolCommand.
 */
sealed class ToolResponse {
    /** Tool executed successfully. */
    data class Success(
        val output: String,
        val metadata: Map<String, Any> = emptyMap()
    ) : ToolResponse()

    /** Tool execution failed. */
    data class Error(
        val code: String,
        val message: String
    ) : ToolResponse()

    /**
     * Tool requires user approval before executing (write, create, append, git commit/add).
     * The UI layer should show a confirmation dialog with the description.
     */
    data class NeedsApproval(
        val description: String,
        val command: ToolCommand,
        val preview: String? = null
    ) : ToolResponse()

    /** Format response for feeding back to LLM context. */
    fun toLlmString(): String = when (this) {
        is Success -> output
        is Error -> "ERROR [$code]: $message"
        is NeedsApproval -> "PENDING_APPROVAL: $description"
    }
}

// ─── Supporting Models ──────────────────────────────────────────────────────

/**
 * A single match from search_grep tool.
 */
data class SearchMatch(
    val file: String,
    val line: Int,
    val content: String
) {
    override fun toString(): String = "$file:$line: $content"
}

/**
 * Statistics from a diff computation.
 */
data class DiffStats(
    val additions: Int,
    val deletions: Int
) {
    val total: Int get() = additions + deletions
    override fun toString(): String = "+$additions / -$deletions"
}

// ─── Sandbox Configuration ──────────────────────────────────────────────────

/**
 * Configuration for the SAS sandbox.
 * Controls security boundaries and resource limits.
 */
data class SasConfig(
    /** Root directory for all file operations. All paths are relative to this. */
    val workingDir: String,

    /** Allowed file extensions (without dot). Empty = allow all. */
    val allowedExtensions: Set<String> = DEFAULT_ALLOWED_EXTENSIONS,

    /** Maximum file size in bytes for read/write operations. */
    val maxFileSizeBytes: Long = DEFAULT_MAX_FILE_SIZE,

    /** Maximum directory depth relative to workingDir. */
    val maxPathDepth: Int = DEFAULT_MAX_DEPTH,

    /** Maximum number of search results from search_grep. */
    val maxSearchResults: Int = DEFAULT_MAX_SEARCH_RESULTS,

    /** Maximum number of entries returned by list_dir. */
    val maxListEntries: Int = DEFAULT_MAX_LIST_ENTRIES,

    /** Maximum lines to display when reading a file. */
    val maxDisplayLines: Int = DEFAULT_MAX_DISPLAY_LINES,

    /** Maximum characters in tool output. */
    val maxOutputChars: Int = DEFAULT_MAX_OUTPUT_CHARS,

    /** System paths that are always blocked. */
    val blockedPrefixes: List<String> = DEFAULT_BLOCKED_PREFIXES,

    /**
     * Maximum number of steps in a single plan.
     * Prevents memory exhaustion on low-end devices by limiting plan complexity.
     */
    val maxStepsPerPlan: Int = DEFAULT_MAX_STEPS_PER_PLAN,

    /**
     * Context token budget.
     * Adapt to model size: 7B → 1024, 13B → 2048, 30B+ → 4096.
     * Use [computeContextBudget] to derive from model parameter count.
     */
    val contextTokenBudget: Int = DEFAULT_CONTEXT_TOKEN_BUDGET,

    /**
     * Maximum number of tool calls per minute (rate limiting).
     * Protects against runaway LLM loops consuming device resources.
     * 0 = unlimited.
     */
    val maxOpsPerMinute: Int = DEFAULT_MAX_OPS_PER_MINUTE
) {
    companion object {
        val DEFAULT_ALLOWED_EXTENSIONS = setOf(
            "java", "kt", "kts", "cpp", "c", "h", "hpp",
            "py", "md", "txt", "xml", "gradle",
            "json", "yaml", "yml", "toml",
            "properties", "pro", "cfg", "gitignore",
            "sh", "bat", "rs", "go", "js", "ts",
            "html", "css", "scss", "svg"
        )

        val DEFAULT_BLOCKED_PREFIXES = listOf(
            "/system", "/data/data", "/proc", "/dev",
            "/etc", "/sbin", "/vendor"
        )

        const val DEFAULT_MAX_FILE_SIZE = 5L * 1024 * 1024  // 5 MB
        const val DEFAULT_MAX_DEPTH = 20
        const val DEFAULT_MAX_SEARCH_RESULTS = 50
        const val DEFAULT_MAX_LIST_ENTRIES = 50
        const val DEFAULT_MAX_DISPLAY_LINES = 100
        const val DEFAULT_MAX_OUTPUT_CHARS = 4000
        const val DEFAULT_MAX_STEPS_PER_PLAN = 10
        const val DEFAULT_CONTEXT_TOKEN_BUDGET = 1024
        const val DEFAULT_MAX_OPS_PER_MINUTE = 60

        /**
         * Derive a context budget appropriate for a model by parameter count.
         * Small models get tighter budgets to leave more room for generation.
         *
         * @param modelParamsBillions Approximate parameter count in billions (e.g. 7.0, 13.0, 32.0)
         * @return Recommended context token budget
         */
        fun computeContextBudget(modelParamsBillions: Float): Int = when {
            modelParamsBillions < 10f  -> 1024   // 7B
            modelParamsBillions < 20f  -> 2048   // 13B
            modelParamsBillions < 40f  -> 3072   // 30B
            else                       -> 4096   // 70B+
        }
    }
}

// ─── Git Operations Interface ───────────────────────────────────────────────

/**
 * Abstraction over git operations for testability and portability.
 * Implementation can use JGit, command-line git, or a mock.
 */
interface GitOperations {
    fun isGitRepo(path: String): Boolean
    fun getStatus(repoPath: String): String
    fun addFiles(repoPath: String, files: List<String>): String
    fun addAll(repoPath: String): String
    fun commit(repoPath: String, message: String): String
    fun getLog(repoPath: String, maxCount: Int): String
    fun getCurrentBranch(repoPath: String): String

    // v3.1 — Extended Git operations (default = UnsupportedOperationException for backward compat)

    /** Detailed status with modified/staged/untracked sections + ahead/behind counts. */
    fun getDetailedStatus(repoPath: String): String =
        throw UnsupportedOperationException("getDetailedStatus not implemented")

    /** Generate a commit message heuristically from current staged changes. */
    fun generateCommitMessage(repoPath: String): String =
        throw UnsupportedOperationException("generateCommitMessage not implemented")

    /** Push to remote. Returns push result summary. */
    fun push(repoPath: String, remote: String = "origin", branch: String? = null): String =
        throw UnsupportedOperationException("push not implemented")

    /** Get ahead/behind counts relative to remote tracking branch. */
    fun getAheadBehind(repoPath: String): Pair<Int, Int> =
        throw UnsupportedOperationException("getAheadBehind not implemented")

    /** Create a new branch. */
    fun createBranch(repoPath: String, name: String): String =
        throw UnsupportedOperationException("createBranch not implemented")

    /** Checkout (switch to) a branch. */
    fun checkoutBranch(repoPath: String, name: String): String =
        throw UnsupportedOperationException("checkoutBranch not implemented")

    /** Delete a local branch. */
    fun deleteBranch(repoPath: String, name: String): String =
        throw UnsupportedOperationException("deleteBranch not implemented")

    /** Merge a branch into current branch. */
    fun mergeBranch(repoPath: String, branchName: String): String =
        throw UnsupportedOperationException("mergeBranch not implemented")

    /** Save current changes to stash. */
    fun stashSave(repoPath: String, message: String? = null): String =
        throw UnsupportedOperationException("stashSave not implemented")

    /** Pop latest stash entry. */
    fun stashPop(repoPath: String): String =
        throw UnsupportedOperationException("stashPop not implemented")

    /** List all stash entries. */
    fun stashList(repoPath: String): String =
        throw UnsupportedOperationException("stashList not implemented")
}

// ─── Bridge State (SasBridge → UI) ──────────────────────────────────────────

/**
 * State of the SAS bridge, exposed as StateFlow to the UI layer.
 * Drives terminal view updates and user interaction.
 */
sealed class BridgeState {
    /** No active operation. Ready for new commands. */
    data object Idle : BridgeState()

    /** Executing a tool command. UI should show spinner. */
    data class Processing(
        val command: ToolCommand,
        val message: String = "Executing ${command.tool.toolName}..."
    ) : BridgeState()

    /** Waiting for user to approve/reject a destructive operation. */
    data class WaitingApproval(
        val command: ToolCommand,
        val description: String,
        val preview: String? = null
    ) : BridgeState()

    /** Agent loop is running — generating + executing in a cycle. */
    data class AgentRunning(
        val currentRound: Int,
        val maxRounds: Int,
        val lastToolName: String? = null
    ) : BridgeState()

    /** An error occurred during execution. */
    data class Error(
        val code: String,
        val message: String,
        val retryCommand: ToolCommand? = null
    ) : BridgeState()
}

// ─── Agent Conversation Round ───────────────────────────────────────────────

/**
 * A single round in the agent conversation loop.
 * Tracks what the LLM generated, what tool was invoked, and the result.
 */
data class AgentRound(
    val roundNumber: Int,
    val llmOutput: String,
    val thought: String? = null,
    val command: ToolCommand? = null,
    val response: ToolResponse? = null,
    val timestamp: Long = System.currentTimeMillis()
)

// ─── File History Snapshot ──────────────────────────────────────────────────

/**
 * A snapshot of a file's state at a point in time.
 * Used by [FileHistoryManager] for undo/redo operations.
 */
data class FileSnapshot(
    /** Relative path from working directory. */
    val path: String,
    /** Timestamp when the snapshot was taken (millis). */
    val timestamp: Long = System.currentTimeMillis(),
    /** File content at snapshot time. Null if file didn't exist (creation snapshot). */
    val content: String?,
    /** File size in bytes at snapshot time. */
    val sizeBytes: Long = content?.toByteArray()?.size?.toLong() ?: 0L
)

// ─── Parsed LLM Output ─────────────────────────────────────────────────────

/**
 * Result of parsing LLM output in mixed mode.
 * LLM may produce text + JSON command in a single message.
 */
data class ParsedLlmOutput(
    /** Plain text portions (chat message to show user). Empty if output was pure JSON. */
    val textParts: List<String> = emptyList(),
    /** Parsed tool command, if found. Null if output was pure text. */
    val command: ToolCommand? = null,
    /** Whether the LLM signaled completion (DONE). */
    val isDone: Boolean = false
) {
    /** True if there is displayable text for the user. */
    val hasText: Boolean get() = textParts.isNotEmpty()
    /** True if a tool command was detected. */
    val hasCommand: Boolean get() = command != null
    /** Combined text output for display. */
    val displayText: String get() = textParts.joinToString("\n").trim()
}

// ─── Code Validation ────────────────────────────────────────────────────────

/**
 * Language detected from file extension.
 */
enum class CodeLanguage(val extensions: Set<String>) {
    KOTLIN(setOf("kt", "kts")),
    JAVA(setOf("java")),
    PYTHON(setOf("py")),
    CPP(setOf("cpp", "c", "h", "hpp")),
    JAVASCRIPT(setOf("js", "ts")),
    XML(setOf("xml")),
    RUST(setOf("rs")),
    GO(setOf("go")),
    UNKNOWN(emptySet());

    companion object {
        fun fromExtension(ext: String): CodeLanguage =
            entries.firstOrNull { ext.lowercase() in it.extensions } ?: UNKNOWN
    }
}

/**
 * Result of code validation before writing.
 */
data class ValidationResult(
    /** Whether the code passed all checks. */
    val valid: Boolean,
    /** List of issues found (empty if valid). */
    val errors: List<ValidationError> = emptyList(),
    /** List of warnings (non-blocking). */
    val warnings: List<String> = emptyList(),
    /** Auto-fixed content if fixes were applied. Null if no fixes needed or not fixable. */
    val autoFixed: String? = null
) {
    /** True if any error has CRITICAL severity (should block writes). */
    val hasCritical: Boolean get() = errors.any { it.severity == ValidationSeverity.CRITICAL }
}

/**
 * A specific validation error.
 */
data class ValidationError(
    val type: ValidationType,
    val message: String,
    val line: Int? = null,
    val severity: ValidationSeverity = ValidationSeverity.ERROR
)

enum class ValidationType {
    UNMATCHED_BRACKET,
    UNCLOSED_STRING,
    STRUCTURAL_REGRESSION,
    CONTENT_LOSS,
    ENCODING_ERROR,
    EMPTY_CONTENT
}

enum class ValidationSeverity {
    WARNING, ERROR, CRITICAL
}

// ─── Hook System (v3.1) ─────────────────────────────────────────────────────

/**
 * Type of hook: fires before or after the main tool execution.
 */
enum class HookType { PRE_COMMAND, POST_COMMAND }

/**
 * Configuration for an automatic hook.
 *
 * A hook is an internal SAS tool command that fires automatically
 * when a trigger tool executes. Hooks are SAS-internal only (not shell commands).
 *
 * Example: auto-format after every write to a Kotlin file
 * ```kotlin
 * HookConfig(
 *     hookType = HookType.POST_COMMAND,
 *     triggerTool = ToolType.WRITE_FILE,
 *     hookAction = ToolCommand(tool = ToolType.FORMAT_FILE, args = mapOf("path" to "\$TARGET_PATH")),
 *     description = "Auto-format Kotlin files after write",
 *     condition = HookCondition.PathExtension(setOf("kt", "kts"))
 * )
 * ```
 *
 * Placeholder `$TARGET_PATH` is resolved from the triggering command's `path` arg.
 */
data class HookConfig(
    val hookType: HookType,
    val triggerTool: ToolType,
    val hookAction: ToolCommand,
    val enabled: Boolean = true,
    val description: String = "",
    /**
     * Optional condition that must be true for the hook to fire.
     * Null = always fire (previous behavior, preserved for backward compatibility).
     */
    val condition: HookCondition? = null,
    /**
     * Execution priority. Lower number = runs first when multiple hooks match.
     * Default 0.
     */
    val priority: Int = 0
)

/**
 * Condition evaluated before a hook fires.
 * When the condition is not met, the hook is silently skipped.
 */
sealed class HookCondition {
    /**
     * Hook fires only if the trigger command's `path` argument has one of the
     * specified file extensions (without the dot).
     *
     * Example: `PathExtension(setOf("kt", "kts"))` fires only on Kotlin files.
     */
    data class PathExtension(val extensions: Set<String>) : HookCondition()

    /**
     * Hook fires only if the trigger command's `path` argument matches the given regex.
     *
     * Example: `PathPattern(Regex("src/.*\\.kt$"))` fires only for .kt files under src/.
     */
    data class PathPattern(val pattern: Regex) : HookCondition()

    /**
     * Hook fires only when a tool response SUCCESS output contains the given substring.
     * Useful for post-hooks that should only run when the tool output indicates an issue.
     *
     * Example: `OutputContains("WARNING")` fires only when the previous tool emitted a warning.
     */
    data class OutputContains(val substring: String, val ignoreCase: Boolean = true) : HookCondition()
}

// ─── Linting Models (v3.1) ──────────────────────────────────────────────────

enum class LintSeverity { INFO, WARNING, ERROR }

/**
 * A single lint issue found by the regex-based linter.
 */
data class LintIssue(
    val rule: String,
    val message: String,
    val file: String,
    val line: Int,
    val severity: LintSeverity = LintSeverity.WARNING
)
