import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.hilt.android)
    alias(libs.plugins.ksp)
}

// ---------------------------------------------------------------------------
// Vulkan / host toolchain setup
// ---------------------------------------------------------------------------

val localProps = Properties().apply {
    val f = rootProject.file("local.properties")
    if (f.exists()) load(f.inputStream())
}
val sdkDirStr = localProps.getProperty("sdk.dir", "").replace("\\", "/")

// Find the highest-version NDK directory
val ndkRoot = file("$sdkDirStr/ndk")
val ndkVersionDir: File? = if (ndkRoot.exists()) {
    ndkRoot.listFiles()
        ?.filter { it.isDirectory }
        ?.sortedByDescending { it.name }
        ?.firstOrNull()
} else null
val ndkDir = ndkVersionDir?.absolutePath?.replace("\\", "/") ?: ""

// glslc from NDK (used by vulkan-shaders-gen to compile GLSL → SPIR-V)
val glslcPath: String = if (ndkDir.isNotEmpty()) {
    "$ndkDir/shader-tools/windows-x86_64/glslc.exe".also { p ->
        if (!file(p).exists()) println("WARNING: glslc not found at $p")
    }
} else ""

// MinGW g++ for compiling vulkan-shaders-gen (Windows x86_64 host tool)
// Keep infra ready — cross-compile works, but Adreno driver throws exception at runtime
val mingwCxx: String = listOf(
    "C:/msys64/mingw64/bin/g++.exe",
    "C:/msys64/ucrt64/bin/g++.exe",
    "C:/mingw64/bin/g++.exe"
).firstOrNull { file(it).exists() } ?: ""
val mingwCc: String = mingwCxx.replace("g++", "gcc")

// Write host toolchain cmake file (consumed by GGML_VULKAN_SHADERS_GEN_TOOLCHAIN)
val hostToolchainFile = file("$projectDir/win-host-toolchain.cmake")
// Vulkan DISABLED — vk::Queue::submit: ErrorDeviceLost on Adreno 830 (Snapdragon 8s Gen 4)
// Upstream fix cd18a50 did not fully resolve runtime crash on this device
val vulkanEnabled: Boolean = false
// Qualcomm Hexagon HTP backend — native DSP acceleration for Snapdragon devices
val hexagonEnabled: Boolean = false
val hexagonSdkRoot = "D:/hexagon/6.5.0.0"
val hexagonToolsRoot = "$hexagonSdkRoot/tools/HEXAGON_Tools/19.0.07"
if (vulkanEnabled && mingwCxx.isNotEmpty() && glslcPath.isNotEmpty() && file(glslcPath).exists()) {
    hostToolchainFile.writeText(
        """
        # Auto-generated by build.gradle.kts — do not edit manually
        # Host toolchain for building vulkan-shaders-gen on Windows x86_64
        set(CMAKE_SYSTEM_NAME Windows)
        set(CMAKE_SYSTEM_PROCESSOR x86_64)
        set(CMAKE_C_COMPILER   "${mingwCc.replace("\\", "/")}")
        set(CMAKE_CXX_COMPILER "${mingwCxx.replace("\\", "/")}")
        # Ensure MinGW bin dir is in PATH for cmake configure step
        set(ENV{PATH} "${File(mingwCxx).parent.replace("\\", "/")};${'$'}ENV{PATH}")
        # Statically link the host executable so it doesn't need MinGW DLLs at runtime
        # (Gradle/Ninja env doesn't include MinGW bin dir)
        set(CMAKE_EXE_LINKER_FLAGS "-static" CACHE STRING "" FORCE)
        set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
        set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
        set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
        """.trimIndent()
    )
    println("Vulkan: ENABLED (g++=$mingwCxx, glslc=$glslcPath)")
} else {
    println("Vulkan: DISABLED (Adreno driver incompatibility)")
}

android {
    namespace = "com.quantma.lite"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.quantma.lite"
        minSdk = 31
        targetSdk = 35
        versionCode = 1
        versionName = "1.0.0-lite"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters += listOf("arm64-v8a")
        }

        externalNativeBuild {
            cmake {
                val cmakeArgs = mutableListOf(
                    "-DCMAKE_BUILD_TYPE=Release",
                    "-DGGML_OPENMP=ON",
                    "-DGGML_LLAMAFILE=OFF",
                    "-DBUILD_SHARED_LIBS=ON",
                    "-DGGML_NATIVE=OFF",
                    // KleidiAI: Arm's optimized inference library for arm64-v8a (matmul kernels)
                    // Required for full performance in llama.cpp 3191462+ — disabling causes ~50% regression
                    "-DGGML_CPU_KLEIDIAI=ON"
                )
                if (vulkanEnabled) {
                    // Vulkan GPU backend — requires MinGW host toolchain to build vulkan-shaders-gen
                    cmakeArgs += "-DGGML_VULKAN=ON"
                    cmakeArgs += "-DGGML_VULKAN_SHADERS_GEN_TOOLCHAIN=${hostToolchainFile.absolutePath.replace("\\", "/")}"
                    cmakeArgs += "-DVulkan_GLSLC_EXECUTABLE=${glslcPath}"
                    // Pass MinGW bin dir so ExternalProject build step can add it to PATH
                    // (Gradle/Ninja's env doesn't include MinGW — g++ can't find its DLLs)
                    val mingwBinDir = File(mingwCxx).parent.replace("\\", "/")
                    cmakeArgs += "-DGGML_VULKAN_SHADERS_GEN_HOST_BIN_DIR=${mingwBinDir}"
                } else {
                    // Fallback: Vulkan disabled (MinGW g++ or glslc not found)
                    cmakeArgs += "-DGGML_VULKAN=OFF"
                }
                if (hexagonEnabled && file(hexagonSdkRoot).exists()) {
                    // Hexagon HTP backend — Qualcomm native DSP inference (Snapdragon 8s Gen 4 → v79/v81)
                    cmakeArgs += "-DGGML_HEXAGON=ON"
                    cmakeArgs += "-DHEXAGON_SDK_ROOT=$hexagonSdkRoot"
                    cmakeArgs += "-DHEXAGON_TOOLS_ROOT=$hexagonToolsRoot"
                    cmakeArgs += "-DGGML_HEXAGON_FP32_QUANTIZE_GROUP_SIZE=128"
                    // Required by hexagon_fun.cmake — prebuilt libs subdir for Android ARM64 target
                    // Corresponds to $hexagonSdkRoot/ipc/fastrpc/remote/ship/android_aarch64/
                    cmakeArgs += "-DPREBUILT_LIB_DIR=android_aarch64"
                    println("Hexagon: ENABLED (sdk=$hexagonSdkRoot)")
                } else {
                    println("Hexagon: DISABLED (SDK not found at $hexagonSdkRoot)")
                }
                arguments(*cmakeArgs.toTypedArray())
            }
        }
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "4.1.2"
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    testOptions {
        unitTests.isReturnDefaultValues = true
    }

    packaging {
        resources {
            excludes += listOf(
                "META-INF/DEPENDENCIES",
                "META-INF/LICENSE",
                "META-INF/LICENSE.txt",
                "META-INF/NOTICE",
                "META-INF/NOTICE.txt"
            )
        }
    }
}

dependencies {
    // Compose
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.material3)
    implementation(libs.compose.icons.extended)
    implementation(libs.compose.ui.tooling.preview)
    debugImplementation(libs.compose.ui.tooling)

    // Core
    implementation(libs.core.ktx)
    implementation(libs.activity.compose)
    implementation(libs.appcompat)

    // Lifecycle
    implementation(libs.lifecycle.runtime.compose)
    implementation(libs.lifecycle.viewmodel.compose)

    // Navigation
    implementation(libs.navigation.compose)

    // Hilt
    implementation(libs.hilt.android)
    ksp(libs.hilt.compiler)
    implementation(libs.hilt.navigation.compose)

    // Room
    implementation(libs.room.runtime)
    implementation(libs.room.ktx)
    ksp(libs.room.compiler)

    // Coroutines
    implementation(libs.coroutines.core)
    implementation(libs.coroutines.android)

    // DataStore
    implementation(libs.datastore.preferences)

    // JGit
    implementation(libs.jgit)

    // Security (encrypted credentials)
    implementation(libs.security.crypto)

    // Diff Utils (Phase 6 v1.5.0)
    implementation(libs.java.diff.utils)

    // Biometric (Phase 8 v1.7.0)
    implementation(libs.biometric)

    // Logging (v2.8.0)
    implementation(libs.timber)

    // Desugaring (required by JGit for java.time.Instant on Android < 13)
    coreLibraryDesugaring(libs.desugar.jdk.libs)

    // Unit tests (pure JVM — no Android runtime needed for data/inference/agent logic)
    testImplementation(libs.junit)
}
