# Auto-generated by build.gradle.kts — do not edit manually
# Host toolchain for building vulkan-shaders-gen on Windows x86_64
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_C_COMPILER   "C:/msys64/mingw64/bin/gcc.exe")
set(CMAKE_CXX_COMPILER "C:/msys64/mingw64/bin/g++.exe")
# Ensure MinGW bin dir is in PATH for cmake configure step
set(ENV{PATH} "C:/msys64/mingw64/bin;$ENV{PATH}")
# Statically link the host executable so it doesn't need MinGW DLLs at runtime
# (Gradle/Ninja env doesn't include MinGW bin dir)
set(CMAKE_EXE_LINKER_FLAGS "-static" CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)